
INSERT INTO BPM_CATEGORY(ID,NAME,PRIORITY) VALUES(1,'常用流程',1);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,NEED_TASK_CONF) VALUES(1,'请假流程',1,'通用请假流程',1,0);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,NEED_TASK_CONF) VALUES(2,'权限审批',2,'权限审批流程',1,0);
